### PR TITLE
Action message for Planner

### PR DESCRIPTION
**Pull request by asaba96**
Plan requests action message for planner.

### CODE REVIEW

**Comment by asaba96** [comment]
Before anyone asks, I considered using the motion points for the request, but felt these were too large and unnecessary for what we need for version 1.0 of the planner.

**Comment by amiller27** [comment]
Looks good.  I wouldn't use a `MotionPointStampedArray` for the request, but you could use a `MotionPointStamped`, it isn't any larger than what you have there.  One other consideration would be whether this can plan towards a moving target (like a roomba), have you or Adriena given any thought towards that?  We can always add that to the message later

**Comment by aftersomemath** [comment]
I agree on using a MotionPointStamped its identical with what you have just with extra fields. Also in terms of software design it makes things more granular so portions of the request can be passed around if necessary.

In the case of the roomba, wouldn't that require the planner to estimate the final state of the roomba and attempt to minimize the error between position and velocity? Wouldn't that be a major change (though not fundamental)?

**Comment by aftersomemath** [comment]
Also, typically we point Action messages in their respective packages. I'm thinking that this should be the same? Not sure how other ROS packages handle this.

**Comment by amiller27** [comment]
The planner would just assume the roomba's velocity is constant for planning purposes.  It isn't that major of a change to rip through and do, but it might be hard depending on how their stuff is implemented and how easy it is to read

**Comment by amiller27** [comment]
I think the action message should be in here.  Dependency inversion and whatnot

**Comment by asaba96** [comment]
My thought would be that the task would do that sort of interpolation and then requests could be made around the estimated final roomba position. We could make the planner have a general track a moving target option (where we receive a callback with the changing positions i.e. roomba callback) but to make the planner so specific as to say track this roomba might be bad from a design perspective.

**Comment by amiller27** [comment]
No the planner can handle this better than any task can, it's inherent to the planning process.  If we can't get it in the planner we can do what you're saying, but that's kinda a hack.

As far as messages, all the actions I can find on my system are in separate `*_msgs` packages.

**Comment by amiller27** [comment]
And yes we could make the planner have an option to hit a target with a constant velocity, we wouldn't have to give it a roomba id.  We probably shouldn't give it a roomba id.

**Comment by asaba96** [comment]
Uses motion point message now

**Pull request merged**
