### PR TITLE
Fixed bool datatype in FlightControllerStatus message

### PR DESCRIPTION
**Pull request by amiller27**

### CODE REVIEW

**Comment by aftersomemath** [comment]
Merging this will break the build, accompanying changes need to be made in fc_comms since it used these as uint8's

**Comment by amiller27** [comment]
Do you want to do that or should I?

**Comment by aftersomemath** [comment]
@Riteshlogin says he will take care of it

**Comment by Riteshlogin** [comment]
For this method - FcCommsReturns getStatus(uint8_t& armed, uint8_t& auto_pilot, uint8_t& failsafe); - do I need to make uint8_t& auto_pilot a bool& auto_pilot now, or is it just bool auto_pilot? I don't know if the bool type follows that pass by reference rule.

Also, do I need to start a new branch for this?

**Pull request merged**
